import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Send, Loader2, Sparkles, Bot, User, Plus, Dumbbell } from 'lucide-react';
import { useUIStore } from '../store';
import { useAuth } from '../context/AuthContext';
import api from '../services/api';
import { workoutService, goalService } from '../services/firestore';

export default function AIChatPanel() {
  const navigate = useNavigate();
  const { chatOpen, setChatOpen } = useUIStore();
  const { user } = useAuth();
  const [messages, setMessages] = useState([
    {
      role: 'assistant',
      content: "Hey! I'm your workout assistant. Ask me about your training, or say 'generate a workout' and I'll create one you can save.",
    },
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [savingWorkout, setSavingWorkout] = useState(null);
  const [context, setContext] = useState({ recentWorkouts: [], goals: [] });
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  useEffect(() => {
    if (chatOpen) {
      inputRef.current?.focus();
      // Load user context when chat opens
      loadUserContext();
    }
  }, [chatOpen]);

  const loadUserContext = async () => {
    if (!user) return;
    try {
      const [workouts, goals] = await Promise.all([
        workoutService.getByUser(user.uid, 10),
        goalService.getByUser(user.uid),
      ]);
      setContext({
        recentWorkouts: workouts.map(w => ({
          name: w.name,
          date: w.date?.toDate ? w.date.toDate().toISOString().split('T')[0] : w.date,
          exercises: w.exercises?.map(e => ({
            name: e.name,
            sets: e.sets?.map(s => ({
              weight: s.actualWeight || s.prescribedWeight,
              reps: s.actualReps || s.prescribedReps,
              rpe: s.rpe
            }))
          }))
        })),
        goals: goals.filter(g => g.status === 'active').map(g => ({
          lift: g.lift,
          currentWeight: g.currentWeight,
          targetWeight: g.targetWeight,
          targetDate: g.targetDate
        }))
      });
    } catch (error) {
      console.error('Error loading user context:', error);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!input.trim() || loading) return;

    const userMessage = input.trim();
    setInput('');
    setMessages((prev) => [...prev, { role: 'user', content: userMessage }]);
    setLoading(true);

    try {
      const response = await api.askAssistant(userMessage, {
        userId: user?.uid,
        recentWorkouts: context.recentWorkouts,
        goals: context.goals,
      });

      setMessages((prev) => [
        ...prev,
        { 
          role: 'assistant', 
          content: response.message,
          workout: response.workout // Include workout data if present
        },
      ]);
    } catch (error) {
      setMessages((prev) => [
        ...prev,
        {
          role: 'assistant',
          content: "Sorry, I couldn't process that. Please try again.",
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  const handleSaveWorkout = async (workout, messageIndex) => {
    if (!user || !workout) return;
    
    setSavingWorkout(messageIndex);
    try {
      // Format the workout for saving
      const workoutData = {
        name: workout.name || 'AI Generated Workout',
        date: new Date(),
        exercises: workout.exercises.map((ex, i) => ({
          id: Date.now() + i,
          name: ex.name,
          sets: ex.sets.map((set, j) => ({
            id: Date.now() + i * 100 + j,
            prescribedWeight: set.prescribedWeight?.toString() || '',
            prescribedReps: set.prescribedReps?.toString() || '',
            actualWeight: '',
            actualReps: '',
            rpe: '',
            painLevel: 0
          })),
          notes: ex.notes || ''
        })),
        notes: 'Generated by AI Assistant',
        status: 'scheduled'
      };

      const saved = await workoutService.create(user.uid, workoutData);
      
      // Update the message to show it was saved
      setMessages(prev => prev.map((msg, idx) => 
        idx === messageIndex 
          ? { ...msg, workoutSaved: true, savedWorkoutId: saved.id }
          : msg
      ));
    } catch (error) {
      console.error('Error saving workout:', error);
      alert('Failed to save workout');
    } finally {
      setSavingWorkout(null);
    }
  };

  const quickActions = [
    "Generate a push workout",
    "What should I do today?",
    "Suggest weights for bench",
    "How's my progress?",
  ];

  return (
    <AnimatePresence>
      {chatOpen && (
        <>
          {/* Backdrop for mobile */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setChatOpen(false)}
            className="lg:hidden fixed inset-0 bg-black/60 backdrop-blur-sm z-40"
          />

          {/* Chat Panel */}
          <motion.div
            initial={{ opacity: 0, x: 20, scale: 0.95 }}
            animate={{ opacity: 1, x: 0, scale: 1 }}
            exit={{ opacity: 0, x: 20, scale: 0.95 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="fixed inset-4 lg:inset-auto lg:bottom-6 lg:right-6 lg:w-96 lg:h-[600px]
              bg-iron-900 border border-iron-700/50 rounded-2xl z-50
              flex flex-col overflow-hidden shadow-2xl"
          >
            {/* Header */}
            <div className="flex items-center justify-between px-4 py-3 border-b border-iron-800">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-full bg-flame-500/20 flex items-center justify-center">
                  <Sparkles className="w-4 h-4 text-flame-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-iron-100">AI Assistant</h3>
                  <p className="text-xs text-iron-500">Always here to help</p>
                </div>
              </div>
              <button
                onClick={() => setChatOpen(false)}
                className="p-2 text-iron-400 hover:text-iron-100 hover:bg-iron-800
                  rounded-full transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4 scrollbar-hide">
              {messages.map((message, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`flex gap-3 ${message.role === 'user' ? 'flex-row-reverse' : ''}`}
                >
                  <div
                    className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0
                      ${message.role === 'user'
                        ? 'bg-flame-500'
                        : 'bg-iron-800 border border-iron-700'
                      }`}
                  >
                    {message.role === 'user' ? (
                      <User className="w-4 h-4 text-white" />
                    ) : (
                      <Bot className="w-4 h-4 text-flame-400" />
                    )}
                  </div>
                  <div className="max-w-[85%] space-y-2">
                    <div
                      className={`px-4 py-2.5 rounded-2xl text-sm
                        ${message.role === 'user'
                          ? 'bg-flame-500 text-white rounded-tr-md'
                          : 'bg-iron-800 text-iron-100 rounded-tl-md'
                        }`}
                    >
                      {message.content}
                    </div>
                    
                    {/* Workout Card */}
                    {message.workout && (
                      <div className="bg-iron-800/50 border border-iron-700 rounded-xl p-3 space-y-2">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Dumbbell className="w-4 h-4 text-flame-400" />
                            <span className="font-medium text-iron-100 text-sm">
                              {message.workout.name}
                            </span>
                          </div>
                          <span className="text-xs text-iron-500">
                            {message.workout.exercises?.length} exercises
                          </span>
                        </div>
                        
                        <div className="text-xs text-iron-400 space-y-1">
                          {message.workout.exercises?.slice(0, 3).map((ex, i) => (
                            <div key={i}>
                              • {ex.name}: {ex.sets?.length} sets
                            </div>
                          ))}
                          {message.workout.exercises?.length > 3 && (
                            <div className="text-iron-500">
                              +{message.workout.exercises.length - 3} more...
                            </div>
                          )}
                        </div>
                        
                        {message.workoutSaved ? (
                          <button
                            onClick={() => {
                              setChatOpen(false);
                              navigate(`/workouts/${message.savedWorkoutId}`);
                            }}
                            className="w-full py-2 bg-green-500/20 text-green-400 rounded-lg text-sm font-medium flex items-center justify-center gap-2"
                          >
                            ✓ Saved - View Workout
                          </button>
                        ) : (
                          <button
                            onClick={() => handleSaveWorkout(message.workout, index)}
                            disabled={savingWorkout === index}
                            className="w-full py-2 bg-flame-500/20 hover:bg-flame-500/30 text-flame-400 rounded-lg text-sm font-medium flex items-center justify-center gap-2 transition-colors disabled:opacity-50"
                          >
                            {savingWorkout === index ? (
                              <>
                                <Loader2 className="w-4 h-4 animate-spin" />
                                Saving...
                              </>
                            ) : (
                              <>
                                <Plus className="w-4 h-4" />
                                Add to My Workouts
                              </>
                            )}
                          </button>
                        )}
                      </div>
                    )}
                  </div>
                </motion.div>
              ))}

              {loading && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex gap-3"
                >
                  <div className="w-8 h-8 rounded-full bg-iron-800 border border-iron-700
                    flex items-center justify-center">
                    <Bot className="w-4 h-4 text-flame-400" />
                  </div>
                  <div className="bg-iron-800 px-4 py-3 rounded-2xl rounded-tl-md">
                    <div className="flex gap-1">
                      <span className="w-2 h-2 rounded-full bg-iron-500 animate-bounce" style={{ animationDelay: '0ms' }} />
                      <span className="w-2 h-2 rounded-full bg-iron-500 animate-bounce" style={{ animationDelay: '150ms' }} />
                      <span className="w-2 h-2 rounded-full bg-iron-500 animate-bounce" style={{ animationDelay: '300ms' }} />
                    </div>
                  </div>
                </motion.div>
              )}

              <div ref={messagesEndRef} />
            </div>

            {/* Quick Actions */}
            {messages.length <= 2 && (
              <div className="px-4 pb-2">
                <p className="text-xs text-iron-500 mb-2">Quick actions</p>
                <div className="flex flex-wrap gap-2">
                  {quickActions.map((action, index) => (
                    <button
                      key={index}
                      onClick={() => setInput(action)}
                      className="px-3 py-1.5 text-xs bg-iron-800 text-iron-300
                        border border-iron-700 rounded-full
                        hover:border-flame-500/50 hover:text-iron-100
                        transition-colors"
                    >
                      {action}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Input */}
            <form
              onSubmit={handleSubmit}
              className="p-4 border-t border-iron-800"
            >
              <div className="flex gap-2">
                <input
                  ref={inputRef}
                  type="text"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  placeholder="Ask about your workouts..."
                  className="flex-1 bg-iron-800 text-iron-100 px-4 py-2.5 rounded-full
                    border border-iron-700 focus:border-flame-500/50 focus:outline-none
                    placeholder:text-iron-500 text-sm"
                />
                <button
                  type="submit"
                  disabled={!input.trim() || loading}
                  className="w-10 h-10 rounded-full bg-flame-500 text-white
                    flex items-center justify-center
                    hover:bg-flame-400 disabled:opacity-50 disabled:cursor-not-allowed
                    transition-colors"
                >
                  {loading ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <Send className="w-4 h-4" />
                  )}
                </button>
              </div>
            </form>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}